### ISSUE TITLE
Overview für SCRUM

### ISSUE THREAD

**Issue by metalmatze** [7Pros/META#17]

**Comment by Gjum** [comment]
Duplicate? #14

**Comment by metalmatze** [comment]
Nein, das ist eine SVG Darstellung von dem, was wir heute an der Tafel hatten.

**Comment by Gjum** [comment]
Ahh ok :D Bild hier rein?

**Comment by metalmatze** [comment]
![img_20150519_145402](https://cloud.githubusercontent.com/assets/872251/7711638/11b53e22-fe6c-11e4-8cba-a7cadaf71758.jpg)

**Comment by metalmatze** [comment]
@Iotka said she is doing that on the weekend.
