### ISSUE TITLE
Permission-Setup

### ISSUE THREAD

**Issue by Gjum** [7Pros/META#18]
- [x] keiner kann nach `circuit` pushen, nur Pull-Requests
  - GitHub lässt dann auch nicht zu, dass Issues geschlossen werden, außer in einem gepullten Commit steht `closes #123`
- [x] jeder kann Issues in `META` schließen

**Comment by metalmatze** [comment]
:+1:

**Comment by Gjum** [comment]
Update:
GitHub lässt jetzt auch nicht zu, dass `circles`-Issues geschlossen werden.
Wenn aber in einem Commit steht `closes #123`, wird die Issue `#123` bei Merge geschlossen.

**Comment by Gjum** [comment]
Siehe auch: [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)
