### ISSUE TITLE
Wöchentlichen Termin festlegen

### ISSUE THREAD

**Issue by levigeiser** [7Pros/META#19]
Doodle auswerten und Termin verkünden

**Comment by Gjum** [comment]
Doodle ist von allen ausgefüllt. Wann setzen wir die Termine?

**Comment by Iotka** [comment]
Hey ich würde vorschlagen, dass jemand Levis Part übernimmt, da er momentan nicht absehbar gesundheitlich in der Lage sein wird ihn zu übernehmen.
