### ISSUE TITLE
Gitter - you do not belong to this organization.

### ISSUE THREAD

**Issue by metalmatze** [7Pros/META#3]
Gitter says this to me: _You've tried to access 7Pros's private organization room and you do not belong to this organization._. Even though I've received an email saying that @Gjum added me to the group...

**Comment by Gjum** [comment]
Huh? Gitter even proposed to invite you... strange...

Well, I hat do add the Organization chat manually, while usually Gitter offers to do that automatically, so something strange is happening.

Could some other member please try to access Gitter?

**Comment by metalmatze** [comment]
Funny, I got an email that you wrote something in the chat, but I can't open it...
