### ISSUE TITLE
Zielformulierung

### ISSUE THREAD

**Issue by levigeiser** [7Pros/META#4]
Eine genaue Formulierung des Ziels in Form eines beschreibenden Texts

**Comment by Gjum** [comment]
- Authentifizierung?
- Löschen, Deaktivieren, Nach Zeit löschen?

**Comment by Gjum** [comment]
> Nach außen hin wird eine Schnittstelle (JSON?) ermöglichen, unabhängig von unserer Weboberfläche Posts zu verfassen.

**Comment by Gjum** [comment]
altes Pad: _Erstellen einer Plattform auf der sich Posts verfassen lassen, dessen Sichtbarkeit auf Gruppen von Personen beschränkt ist._
Soll sowas als Anfangsübersicht mit rein?

**Comment by metalmatze** [comment]
Also ich habe nun einiges geschrieben. Ich bin mir nicht sicher, ob da noch mehr dazu muss. [zielformulierung.md](https://github.com/7Pros/META/blob/master/zielformulierung.md)

**Comment by juanecabellob** [comment]
API Geschichte soll auf jeden Fall rein, Responsive und Benutzerfreundlich System soll meiner Meinung nach auch drin stehen.. 
Hat jmd noch weitere Verbesserungsvorschläge?

**Comment by metalmatze** [comment]
API und responsive stimme ich zu. Dass es ein benutzerfreundliches System ist, sollte selbstverständlich sein.

**Comment by metalmatze** [comment]
API und responsive hinzugefügt 12dd5c3

**Comment by Gjum** [comment]
Sehr nice. :+1:

**Comment by juanecabellob** [comment]
Na ja, es ist selbstverständlich für uns, nicht für die PO. Wir setzen uns daher dieses Ziel, aber es sollte auch der Focus sein und dementsprechend auch in der Zielformulierung stehen. Auch ganz kurz erwähnt, ganz am Anfang würde es gut sein

**Comment by juanecabellob** [comment]
Anfang: Circuit ist ein benutzerfreundliches soziales Netzwerk oder beim Satz vom GUI: Die GUI soll benutzerfreundlich und responsive.. Sowas meine ich

**Comment by metalmatze** [comment]
Ich hoffe, dass jeder Entwickler immer mit dem Anspruch an ein Projekt geht, es möglichst benutzerfreundlich zu machen. Das ist so allgemein, dass ich sagen würde, dass wir es nicht explizit nennen sollten.

**Comment by Gjum** [comment]
Lass es uns doch einfach reinschreiben.

**Comment by metalmatze** [comment]
3e5fa7f540dffe632844039a10c2385c863bd22b Ist es so ok?

**Comment by juanecabellob** [comment]
Jo passt. Was sagen die anderen?

**Comment by Gjum** [comment]
:+1:
