### ISSUE TITLE
Aufgabeneinteiung

### ISSUE THREAD

**Issue by levigeiser** [7Pros/META#5]
Es muss eine Einteilung aller Aufgaben, die zum erreichen unseres Ziels nötig sind, vorgenommen werden.

**Comment by juanecabellob** [comment]
http://somepad.de/oxdGDZazxM -> preliminary version of the project development plan.

**Comment by metalmatze** [comment]
Did you use our requirements table to create that document?

**Comment by juanecabellob** [comment]
Yes, but I didn't write everything explicit, maybe that's the only thing missing and of course the extra feature's section..

**Comment by Gjum** [comment]
Wer machts fertig?

**Comment by juanecabellob** [comment]
Ich! wir müssen uns aber an der stelle mal einigen damit ich das zu Ende schreiben kann

**Comment by Gjum** [comment]
@juanecabellob OK, wie machen wir das?

**Comment by juanecabellob** [comment]
@Gjum steht alles in waffle

**Comment by Gjum** [comment]
:+1:

**Comment by Gjum** [comment]
~~close?~~ mh nee, muss ja vorm ersten sprint gemacht werden oder?
