### ISSUE TITLE
Create the product requirements document (If needed)

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/META#9]
After the response of Mr. Scherz will be decided whether a product requirements documents is needed or not. If it's not needed just close the issue.

**Comment by Gjum** [comment]
[Related forum discussion](https://isis.tu-berlin.de/mod/forum/discuss.php?d=55076)

**Comment by Gjum** [comment]
Who will be assigned to check the forums and write the document if needed?

**Comment by juanecabellob** [comment]
@Nico?

**Comment by Gjum** [comment]
Poor Nico, does not have anything to do with this issue...
@juanecabellob Next time, please ping @nrigheriu instead ;)

**Comment by Gjum** [comment]
Closing, as nobody responded in the forums.
